
<div  class="block block-custom-sidebar product-item">
     <div class="block-title">
          <strong><?php echo __($block->getTitleConfig()); ?></strong>
     </div>
     <div class="block-content">
          <p>Sie wünschen ein Tuning oder eine Reparatur Ihrer Airsoftwaffe?</p>
          <p><span>Visit our </span><b><a href="/workshop/frontend/index" target="_blank">airsoft workshop</a> .</b><p>
     </div>
</div>
<style>
.block-custom-sidebar .block-content p{
     text-align: center;
     margin-top: 18px;
}
.block-customer-sidebar{
     background: #CDBFA7;
}
</style>